steps:
  - name: nixos/nix:latest
    entrypoint: '/bin/sh'
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'BUILD_ID=$BUILD_ID'
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'SHORT_SHA=$SHORT_SHA'
      - 'REPO_NAME=$REPO_NAME'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'TAG_NAME=$TAG_NAME'
    args:
      - -c
      - |
        nix-channel --update
        env

        nix-shell pipeline.nix \
                  --pure \
                  --keep PROJECT_ID \
                  --keep BUILD_ID \
                  --keep COMMIT_SHA \
                  --keep SHORT_SHA \
                  --keep REPO_NAME \
                  --keep BRANCH_NAME \
                  --keep TAG_NAME \
                  --run bash <<'NIXSH'

          set -euo pipefail
          env

          test-step

          if on-deploy-branch; then
            deploy-step
          fi

        NIXSH