steps:
  - name: nixorg/nix:latest
    entrypoint: 'bash'
    args:
      - -c
      - |
        nix-channel --add \
        https://nixos.org/channels/nixpkgs-unstable nixpkgs
        nix-channel --update
        env

        nix-shell --pure pipeline.nix --run bash <<'NIXSH'
          set -euo pipefail
          env

          test-step

          if on-deploy-branch; then
            deploy-step
          fi

        NIXSH